### ISSUE TITLE
Synchrony

### ISSUE THREAD

**Issue by elladulko** [thomaskreuz/SPIKY#1]
Hi Thomas! 
I started exploring SPIKY. Thanks for your work! I have spike data and I would like to use spiky to look at synchrony across cells. I saw that I could group my cells and then compare the synchrony between them. But is it possible to look at synchrony across all cells. For example: 1st vs 2nd, ... 20th etc and do it for all of them? I usually get 20-30 cells per structure. If not, is there a way to group them automatically (based on the similarity of their spike trains)? So I'm not biased when I pick? 

Thanks in advance,
Ela

**Comment by thomaskreuz** [comment]
Hi Ela,

please have a look at this video:

https://www.youtube.com/watch?v=Po_YxuHW_ZY&ab_channel=SPIKY

At around 6:18 we explain how we do temporal averaging over the whole interval of your recording. Then you get the pairwise matrix and the dendrogram (as shown in the movie). From the dendrogram you could extract the groups of cells that form clusters. 

Now I remembered that there is actually a faster way included in SPIKY and we did a video of this as well. Check this out:

https://www.youtube.com/watch?v=y9iqYD4UtYE&t=1s&ab_channel=SPIKY

Just let me know if you have any further questions.

Cheers,
Thomas

PS: I would also recommend to see the general introduction to SPIKY:

https://www.youtube.com/watch?v=g0r3LI7eBS0&ab_channel=SPIKY

**Comment by elladulko** [comment]
Thank you! It's very helpful! 
Ela
